# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_of_choice', models.CharField(blank=True, choices=[('laundry', 'laundry'), ('kitchen', 'kitchen'), ('compound', 'compound'), ('ironing', 'ironing'), ('general', 'general')], max_length=30, null=True)),
                ('hours_choice', models.IntegerField()),
                ('rooms', models.CharField(default=1, max_length=6)),
                ('service_summary', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
