# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetservice',
            name='location_of_choice',
            field=models.CharField(blank=True, choices=[('jamhuri_phase_1', 'jamhuri_phase_1'), ('jamhuri_phase_2', 'jamhuri_phase_2'), ('karen', 'karen'), ('hurligham', 'hurligham'), ('kileleshwa', 'kileleshwa'), ('lavington', 'lavington')], max_length=30, null=True),
        ),
    ]
